### ISSUE TITLE
Make GitHub Action script for setting up Metanorma

### ISSUE THREAD

**Issue by ronaldtse** [actions-mn/setup#1]
* Ubuntu
* macOS
* Windows
* Docker

We can use an argument to separate these cases.

**Comment by ronaldtse** [comment]
For @CAMOBAP795 . Thanks!

**Comment by ronaldtse** [comment]
We should mimic something like this: https://github.com/actions-rs

**Comment by ronaldtse** [comment]
Ping @CAMOBAP795

**Comment by CAMOBAP** [comment]
@ronaldtse I need write permissions for this repo

**Comment by ronaldtse** [comment]
Fixed.
