### ISSUE TITLE
Support version input

### ISSUE THREAD

**Issue by CAMOBAP** [actions-mn/setup#5]

**Comment by ronaldtse** [comment]
@CAMOBAP great suggestion. Do we simply use differently versioned containers for this?

**Comment by CAMOBAP** [comment]
@ronaldtse yep I recently add optional input to configure it like in https://github.com/metanorma/mn-samples-gb/blob/main/.github/workflows/docker.yml#L19

Also I temporally removed generate workflow because it always install latest

**Comment by CAMOBAP** [comment]
snap not work, because of specific we never released version channels, but now we do https://github.com/metanorma/metanorma-snap/pull/21
